# Usar imagen base de Python
FROM python:3.10-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivo de requerimientos
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar archivos necesarios
COPY inferencia.py .
COPY preprocessor.pkl .
COPY model.keras .
COPY feature_names.pkl .
COPY coordenadas_aus.csv .

# El script espera input.csv en el directorio actual
# y generará output.csv en el mismo directorio
CMD ["python", "inferencia.py"]